// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AutoFetchAndroidDBRequest carries arguments for AutoFetchAndroidDB.
 */
export interface AutoFetchAndroidDBRequest {
}

/**
 * AutoFetchAndroidDBResponse is the return envelope for AutoFetchAndroidDB.
 */
export interface AutoFetchAndroidDBResponse {
    "path": string;
}

/**
 * CheckWifiUploadRequest carries arguments for CheckWifiUpload.
 */
export interface CheckWifiUploadRequest {
    "token": string;
}

/**
 * CheckWifiUploadResponse is the return envelope for CheckWifiUpload.
 */
export interface CheckWifiUploadResponse {
    "path": string;
}

/**
 * PickAndroidDBManuallyRequest carries arguments for PickAndroidDBManually.
 */
export interface PickAndroidDBManuallyRequest {
}

/**
 * PickAndroidDBManuallyResponse is the return envelope for PickAndroidDBManually.
 */
export interface PickAndroidDBManuallyResponse {
    "path": string;
}

/**
 * ReadAndroidSlotsRequest carries arguments for ReadAndroidSlots.
 */
export interface ReadAndroidSlotsRequest {
    "dbPath": string;
}

/**
 * ReadAndroidSlotsResponse is the return envelope for ReadAndroidSlots.
 */
export interface ReadAndroidSlotsResponse {
    "rows": SlotRow[] | null;
}

/**
 * SlotRow mirrors one record of the `slot` table.
 */
export interface SlotRow {
    "id": number;
    "slotIndex": number;
    "userAccount": string;
    "jsonString": string;
    "jsonSize": number;
    "jsonPreview": string;
}

/**
 * StartWifiServerRequest carries arguments for StartWifiServer.
 */
export interface StartWifiServerRequest {
}

/**
 * StartWifiServerResponse is the return envelope for StartWifiServer.
 */
export interface StartWifiServerResponse {
    "result": WifiResult | null;
}

/**
 * StopWifiServerRequest carries arguments for StopWifiServer.
 */
export interface StopWifiServerRequest {
}

/**
 * StopWifiServerResponse is the return envelope for StopWifiServer.
 */
export interface StopWifiServerResponse {
}

/**
 * WifiResult holds the connection info for the client.
 */
export interface WifiResult {
    /**
     * Best guess URL for phone access
     */
    "url": string;

    /**
     * localhost URL for local testing
     */
    "localUrl": string;

    /**
     * All available IP-based URLs
     */
    "allUrls": string[] | null;
    "token": string;

    /**
     * Debug info for troubleshooting
     */
    "debugInfo": string;

    /**
     * Listening port
     */
    "port": number;

    /**
     * netsh command to add firewall rule
     */
    "firewallCmd": string;
}
