// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AutoFetchAndroidDB extracts the bundled adb, locates a connected device and
 * pulls game.db into a per-user cache directory. Returns the local path.
 */
export function AutoFetchAndroidDB(req: $models.AutoFetchAndroidDBRequest | null): $CancellablePromise<$models.AutoFetchAndroidDBResponse | null> {
    return $Call.ByID(454855022, req);
}

/**
 * CheckWifiUpload polls the Wi-Fi server for upload completion.
 * Returns the local file path when upload is done, empty string otherwise.
 */
export function CheckWifiUpload(req: $models.CheckWifiUploadRequest | null): $CancellablePromise<$models.CheckWifiUploadResponse | null> {
    return $Call.ByID(3384413192, req);
}

/**
 * PickAndroidDBManually opens a file picker so the user can choose a game.db
 * file previously copied to the PC.
 */
export function PickAndroidDBManually(req: $models.PickAndroidDBManuallyRequest | null): $CancellablePromise<$models.PickAndroidDBManuallyResponse | null> {
    return $Call.ByID(1081327591, req);
}

/**
 * ReadAndroidSlots reads all rows from the slot table of the given game.db.
 */
export function ReadAndroidSlots(req: $models.ReadAndroidSlotsRequest | null): $CancellablePromise<$models.ReadAndroidSlotsResponse | null> {
    return $Call.ByID(2947350792, req);
}

/**
 * StartWifiServer starts an HTTP server on the local network for receiving
 * game.db via Wi-Fi upload from the user's phone.
 */
export function StartWifiServer(req: $models.StartWifiServerRequest | null): $CancellablePromise<$models.StartWifiServerResponse | null> {
    return $Call.ByID(4037194490, req);
}

/**
 * StopWifiServer stops the currently running Wi-Fi server.
 */
export function StopWifiServer(req: $models.StopWifiServerRequest | null): $CancellablePromise<$models.StopWifiServerResponse | null> {
    return $Call.ByID(1877468678, req);
}
