// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MigrateRequest carries arguments for Migrate.
 */
export interface MigrateRequest {
    "remotePath": string;
    "selections": SlotSelection[] | null;
}

/**
 * MigrateResponse is the return envelope for Migrate.
 */
export interface MigrateResponse {
    "results": Result[] | null;
}

/**
 * Result MigrateResult is the outcome of migrating one SlotSelection.
 */
export interface Result {
    "id": number;
    "slotIndex": number;
    "targetFile": string;
    "backupFile": string;
    "success": boolean;
    "error": string;
}

/**
 * SlotSelection is a single row chosen by the user for migration.
 */
export interface SlotSelection {
    "id": number;
    "slotIndex": number;
    "jsonString": string;
}
