// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Migrate performs the backup-and-write for each selection. Each selection is
 * processed independently: a failure on one does not stop the others, and the
 * per-item outcome is reported back so the UI can show a precise log.
 * 
 * Backup policy: an existing target file is renamed to
 * `Slot{X}.json.{YYYYMMDD_HHMMSS}.bak`. If a backup with the same name already
 * exists (sub-second retry within the same second), a numeric suffix is appended.
 */
export function Migrate(req: $models.MigrateRequest | null): $CancellablePromise<$models.MigrateResponse | null> {
    return $Call.ByID(2292522135, req);
}
