// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DetectRequest carries arguments for Detect.
 */
export interface DetectRequest {
}

/**
 * DetectResponse is the return envelope for Detect.
 */
export interface DetectResponse {
    "info": Info;
}

/**
 * Info bundles the Steam install path and the discovered user accounts.
 */
export interface Info {
    "steamPath": string;
    "users": User[] | null;
}

/**
 * PickRemoteManuallyRequest carries arguments for PickRemoteManually.
 */
export interface PickRemoteManuallyRequest {
}

/**
 * PickRemoteManuallyResponse is the return envelope for PickRemoteManually.
 */
export interface PickRemoteManuallyResponse {
    "path": string;
}

/**
 * User SteamUser represents one Steam user account that has save data for the game.
 */
export interface User {
    "steamId": string;
    "remotePath": string;
}
