// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Detect is a convenience wrapper returning the full Info.
 */
export function Detect(req: $models.DetectRequest | null): $CancellablePromise<$models.DetectResponse | null> {
    return $Call.ByID(1893933918, req);
}

/**
 * PickRemoteManually opens a directory picker so the user can choose a Steam
 * remote folder manually (e.g. when Steam is installed in a portable location).
 */
export function PickRemoteManually(req: $models.PickRemoteManuallyRequest | null): $CancellablePromise<$models.PickRemoteManuallyResponse | null> {
    return $Call.ByID(1997229051, req);
}
