// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoFetchAndroidDB() {
  return window['go']['main']['App']['AutoFetchAndroidDB']();
}

export function CheckWifiUpload(arg1) {
  return window['go']['main']['App']['CheckWifiUpload'](arg1);
}

export function DetectSteam() {
  return window['go']['main']['App']['DetectSteam']();
}

export function Migrate(arg1, arg2) {
  return window['go']['main']['App']['Migrate'](arg1, arg2);
}

export function PickAndroidDBManually() {
  return window['go']['main']['App']['PickAndroidDBManually']();
}

export function PickRemoteManually() {
  return window['go']['main']['App']['PickRemoteManually']();
}

export function ReadAndroidSlots(arg1) {
  return window['go']['main']['App']['ReadAndroidSlots'](arg1);
}

export function StartWifiServer() {
  return window['go']['main']['App']['StartWifiServer']();
}

export function StopWifiServer() {
  return window['go']['main']['App']['StopWifiServer']();
}
